### ISSUE TITLE
Injecting dependencies seems not to work

### ISSUE THREAD

**Issue by tristanbes** [BehatExtension/DoctrineDataFixturesExtension#22]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | - 
| Project version      | 5.0.1

Hi,

I'm migrating from a Symfony 3 application to `4.1`. It seems that dependency injection is not done. Is this a bug or am I missing something ?

The error is: 

```
Too few arguments to function Context\Fixtures\FixturesLoader::__construct(), 0 passed in /srv/app/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php on line 193 and exactly 2 expected
```

When i'm running: `bin/behat -c apps/behat.yml -p front --tags="front_intro_on_page"`

```yml
// behat.yml

default:
    autoload: '%paths.base%/features/Context'
    extensions:
        Behat\Symfony2Extension:
            kernel:
                env: test
                debug: true
                path: admin/AdminKernel.php
                class: AdminKernel
                bootstrap: vendor/autoload.php
        BehatExtension\DoctrineDataFixturesExtension\Extension:
            lifetime:   feature
            autoload:   false
            use_backup: true
            directories:
                - apps/features/Context/Fixtures
            fixtures: ~
        Behatch\Extension: ~
    suites:
        default:
            contexts:
                - Context\FeatureContext
                - behatch:context:browser
    translation:
        locale: en
```

```php
<?php

namespace Context\Fixtures;

...

class FixturesLoader extends Fixture
{
    private $loader;
    private $doctrine;

    public function __construct(NativeLoader $loader, ManagerRegistry $doctrine)
    {
        $this->loader   = $loader;
        $this->doctrine = $doctrine;
    }

    /**
     * {@inheritdoc}
     */
    public function load(ObjectManager $manager)
    {
        $objectSet = $this->loader->loadFiles(
            [
                __DIR__.'/companies.yml',
                __DIR__.'/medias.yml',

```

When I run : `bin/console debug:container FixturesLoader --env=test`
it gives me 

```
Information for Service "Context\Fixtures\FixturesLoader"
=========================================================

 ---------------- ---------------------------------
  Option           Value
 ---------------- ---------------------------------
  Service ID       Context\Fixtures\FixturesLoader
  Class            Context\Fixtures\FixturesLoader
  Tags             doctrine.fixture.orm
  Public           yes
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        yes
  Autoconfigured   yes
 ---------------- ---------------------------------
```

But when I run 
`bin/behat -c apps/behat.yml -p front --tags="front_intro_on_page"`

The errors appears
